[package]
name = "first-packet-picker"
version = "0.1.0"
author = "megumish <megumish@exploitouri.st>"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
