[package]
name = "refuic-crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10"
hmac = "0.12"
aes-gcm = "0.10"
thiserror = "1.0"